[package]
name = "ipvs"
version = "0.1.0"
edition = "2021"

[dependencies]
netlink-packet-ipvs = { path = "../netlink-packet-generic" }
netlink-packet-generic = "0.3.3"
netlink-packet-core = { version = "0.7.0" }
netlink-packet-utils = { version = "0.5.2" }
netlink-sys = { version = "0.8.3" }
